comparison_colors = [
    {r = 230, g = 25,  b = 75},   # red
    {r = 60,  g = 180, b = 75},   # green
    {r = 255, g = 225, b = 25},   # yellow
    {r = 0,   g = 130, b = 200},  # blue
    {r = 245, g = 130, b = 48},   # orange
    {r = 145, g = 30,  b = 180},  # purple
    {r = 70,  g = 240, b = 240},  # light cyan
    {r = 240, g = 50,  b = 230},  # magenta
]
